### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by iotnxt** [BrainDriveAI/openwebui-pipelines#1]
Getting a network error when selecting "Chat with YouTube" and asking a question.
Uh-oh! There was an issue connecting to Chat with YouTube.
network error

ollama, openwebui and pipelines are running on docker containers
container name ollama:  http://ollama:11434  
container name pipelines: http://pipelines:9099
container name open-webui on port 3000

the green pop up message confirming connection pops up when I save the pipeline configurations
I can use the other ollama local models with no issues.

thanks

**Comment by bekmuradov** [comment]
Hey @iotnxt ,

Thanks for reporting this issue!

Could you please check the detailed error logs from the `open-webui` container? That should help us identify what might be causing the network error.

**Comment by iotnxt** [comment]
await self.app(scope, receive_or_disconnect, send_no_error)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 148, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 261, in wrap
    await func()
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 217, in stream_response
    return await super().stream_response(send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 250, in stream_response
    async for chunk in self.body_iterator:
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 181, in body_stream
    raise app_exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 261, in wrap
    await func()
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 217, in stream_response
    return await super().stream_response(send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 250, in stream_response
    async for chunk in self.body_iterator:
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 181, in body_stream
    raise app_exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 261, in wrap
    await func()
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 250, in stream_response
    async for chunk in self.body_iterator:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 50, in __anext__
    rv = await self.read_func()
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 320, in readline
    return await self.readuntil()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 354, in readuntil
    await self._wait("readuntil")
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 315, in _wait
    await waiter
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>
ERROR [asyncio] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x798c6eb1fed0>
INFO:     172.20.0.1:41042 - "POST /api/v1/chats/26031f62-4174-4654-9445-b18da57fc457 HTTP/1.1" 200 OK
INFO:     172.20.0.1:41042 - "GET /api/v1/chats/?page=1 HTTP/1.1" 200 OK
INFO  [open_webui.apps.openai.main] get_all_models()
INFO  [open_webui.apps.ollama.main] get_all_models()
[{'models': [{'name': 'nomic-embed-text:latest', 'model': 'nomic-embed-text:latest', 'modified_at': '2024-11-20T04:03:10.025800567Z', 'size': 274302450, 'digest': '0a109f422b47e3a30ba2b10eca18548e944e8a23073ee3f3e947efcf3c45e59f', 'details': {'parent_model': '', 'format': 'gguf', 'family': 'nomic-bert', 'families': ['nomic-bert'], 'parameter_size': '137M', 'quantization_level': 'F16'}}, {'name': 'nemotron-mini:4b-instruct-q3_K_S', 'model': 'nemotron-mini:4b-instruct-q3_K_S', 'modified_at': '2024-11-20T04:02:32.670104243Z', 'size': 2115590322, 'digest': '28cabdeeb76e98b2268440b0a55e81a3a6ce10a28746bbb58185785ed5dd18a6', 'details': {'parent_model': '', 'format': 'gguf', 'family': 'nemotron', 'families': ['nemotron'], 'parameter_size': '4.2B', 'quantization_level': 'Q3_K_S'}}]}]
INFO:     172.20.0.1:41042 - "POST /api/chat/completed HTTP/1.1" 200 OK
INFO:     172.20.0.1:41042 - "POST /api/v1/chats/26031f62-4174-4654-9445-b18da57fc457 HTTP/1.1" 200 OK
INFO:     172.20.0.1:41042 - "GET /api/v1/chats/?page=1 HTTP/1.1" 200 OK
INFO  [open_webui.apps.openai.main] get_all_models()
ERROR [open_webui.apps.openai.main] 500, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url='http://pipelines:9099/chat/completions'
ERROR [open_webui.apps.openai.main] 500, message='Internal Server Error', url='http://pipelines:9099/chat/completions'
Traceback (most recent call last):
  File "/app/backend/open_webui/apps/openai/main.py", line 628, in generate_chat_completion
    r.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1121, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url='http://pipelines:9099/chat/completions'
generate_title
chat-with-youtube-pipeline
INFO:     172.20.0.1:41042 - "POST /api/task/title/completions HTTP/1.1" 500 Internal Server Error
INFO:     172.20.0.1:41042 - "POST /api/v1/chats/26031f62-4174-4654-9445-b18da57fc457 HTTP/1.1" 200 OK
INFO:     172.20.0.1:41042 - "GET /api/v1/chats/?page=1 HTTP/1.1" 200 OK
INFO:     172.20.0.1:41042 - "GET /api/v1/chats/26031f62-4174-4654-9445-b18da57fc457/tags HTTP/1.1" 200 OK
INFO  [open_webui.apps.openai.main] get_all_models()
ERROR [open_webui.apps.openai.main] 500, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url='http://pipelines:9099/chat/completions'
ERROR [open_webui.apps.openai.main] 500, message='Internal Server Error', url='http://pipelines:9099/chat/completions'
Traceback (most recent call last):
  File "/app/backend/open_webui/apps/openai/main.py", line 628, in generate_chat_completion
    r.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1121, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url='http://pipelines:9099/chat/completions'
generate_chat_tags
chat-with-youtube-pipeline
INFO:     172.20.0.1:41042 - "POST /api/task/tags/completions HTTP/1.1" 500 Internal Server Error
INFO:     172.20.0.1:41042 - "GET /api/v1/chats/26031f62-4174-4654-9445-b18da57fc457 HTTP/1.1" 200 OK
INFO:     172.20.0.1:41042 - "GET /api/v1/chats/all/tags HTTP/1.1" 200 OK
INFO:     172.20.0.1:41042 - "GET /api/v1/chats/?page=1 HTTP/1.1" 200 OK

**Comment by bekmuradov** [comment]
Thanks! Could you also share the logs from your pipeline container? Not all of them - just the part where it tried to install our YouTube pipeline.

**Comment by iotnxt** [comment]
is it absolutely necessary to use an OpenAI  Model?
can we use a different model? like Llama3.2. or any other chat model?

**Comment by iotnxt** [comment]
I dont have an OpenAI active account
can this be done with local hosted ollama models, or with model from https://openrouter.ai/
or from https://api.groq.com/openai/v1

this is the output from pipeline container:

    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 780, in generate_openai_chat_completion
    return await run_in_threadpool(job)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 943, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 738, in job
    res = pipe(
          ^^^^^
  File "/app/./pipelines/chat-with-youtube-pipeline.py", line 104, in pipe
    response = agent_executor.invoke({"input": user_message, "chat_history": messages})
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 170, in invoke
    raise e
  File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 160, in invoke
    self._call(inputs, run_manager=run_manager)
  File "/usr/local/lib/python3.11/site-packages/langchain/agents/agent.py", line 1629, in _call
    next_step_output = self._take_next_step(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/agents/agent.py", line 1335, in _take_next_step
    [
  File "/usr/local/lib/python3.11/site-packages/langchain/agents/agent.py", line 1335, in <listcomp>
    [
  File "/usr/local/lib/python3.11/site-packages/langchain/agents/agent.py", line 1363, in _iter_next_step
    output = self._action_agent.plan(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/agents/agent.py", line 580, in plan
    for chunk in self.runnable.stream(inputs, config={"callbacks": callbacks}):
  File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 3407, in stream
    yield from self.transform(iter([input]), config, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 3394, in transform
    yield from self._transform_stream_with_config(
  File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 2197, in _transform_stream_with_config
    chunk: Output = context.run(next, iterator)  # type: ignore
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 3357, in _transform
    yield from final_pipeline
  File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1413, in transform
    for ichunk in input:
  File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 5561, in transform
    yield from self.bound.transform(
  File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 1431, in transform
    yield from self.stream(final, config, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 420, in stream
    raise e
  File "/usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 400, in stream
    for chunk in self._stream(messages, stop=stop, **kwargs):
  File "/usr/local/lib/python3.11/site-packages/langchain_openai/chat_models/base.py", line 634, in _stream
    response = self.client.create(**payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 815, in create
    return self._post(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1277, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 954, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1058, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: 1234. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

**Comment by bekmuradov** [comment]
of course it will work with any LLM provider. We will soon update this pipeline with other LLM integrations.

**Comment by iotnxt** [comment]
I am trying to make it work with a local hosted LLM and is not working.
Just wondering what am I doing wrong.
According to your last video, the changes are supposed to be simple.

"""
title: Chat with YouTube Pipeline
author: Begench Bekmyradov
date: 2024-10-30
version: 1.1
license: MIT
description: A custom pipeline that performs YouTube video search, retrieves transcripts, generates transcript summaries, conducts Q&A over transcripts, and searches within transcript/video content.
requirements: pydantic==2.7.4, requests, youtube-search==2.1.2, youtube-transcript-api==0.6.2, pytube==15.0.0, langchain==0.3.3, langchain-community==0.3.2, langchain-core==0.3.10, langchain-text-splitters==0.3.0, langchain-ollama
"""

import os
import requests
import json
from typing import List, Sequence
from pydantic import BaseModel, Field
from langchain import hub
from langchain_community.llms import Ollama
from langchain.agents import create_tool_calling_agent, AgentExecutor
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.tools import BaseTool, tool

class YoutubeSearchInput(BaseModel):
    query: str = Field(description="Search query for YouTube videos.")

@tool("search_youtube", args_schema=YoutubeSearchInput, return_direct=False)
def search_youtube(query: str) -> str:
    """Search YouTube and return video URLs based on the query."""
    from youtube_search import YoutubeSearch
    results = YoutubeSearch(query, 10).to_json()
    data = json.loads(results)
    return str([
        "https://www.youtube.com" + video["url_suffix"]
        for video in data["videos"]
    ])

class YoutubeTranscriptInput(BaseModel):
    youtube_url: str = Field(description="A valid YouTube video URL.")

@tool("get_youtube_transcript", args_schema=YoutubeTranscriptInput, return_direct=False)
def get_youtube_transcript(youtube_url: str) -> str:
    """Retrieve transcripts from the provided YouTube video URL."""
    from langchain_community.document_loaders import YoutubeLoader
    loader = YoutubeLoader.from_youtube_url(
        youtube_url, add_video_info=False, language=["en"], translation="en"
    )
    return "\n\n".join(map(repr, loader.load()))

class Pipeline:
    class Valves(BaseModel):
        OLLAMA_BASE_URL: str = "http://localhost:11434"
        OLLAMA_MODEL: str = "llama3.2"
        TEMPERATURE: float = 0.7
        AGENT_SYSTEM_PROMPT: str = (
            "You are a smart assistant that searches for YouTube videos, retrieves their transcripts, "
            "analyzes them, and assists users with Q&A over video content."
        )

    def __init__(self):
        self.name = "Chat with YouTube"
        self.tools = None
        self.valves = self.Valves()
        self.pipelines = self.get_ollama_models()

    def get_ollama_models(self):
        try:
            response = requests.get(f"{self.valves.OLLAMA_BASE_URL}/api/tags")
            models = response.json()
            return [
                {"id": model["name"], "name": model["name"]}
                for model in models["models"]
            ]
        except Exception as e:
            print(f"Error: {e}")
            return [{"id": "error", "name": "Could not fetch models from Ollama."}]

    def pipe(self, user_message: str, model_id: str, messages: List[dict], body: dict):
        try:
            model = Ollama(
                base_url=self.valves.OLLAMA_BASE_URL,
                model=self.valves.OLLAMA_MODEL,
                temperature=self.valves.TEMPERATURE
            )
            tools: Sequence[BaseTool] = [search_youtube, get_youtube_transcript]
            prompt = ChatPromptTemplate.from_messages([
                ("system", self.valves.AGENT_SYSTEM_PROMPT),
                MessagesPlaceholder("chat_history"),
                ("user", "{input}"),
                MessagesPlaceholder("agent_scratchpad")
            ])
            agent = create_tool_calling_agent(model, tools, prompt)
            agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True, handle_parsing_errors=True)
            response = agent_executor.invoke({"input": user_message, "chat_history": messages})
            return response["output"]
        except Exception as e:
            print(f"An error occurred: {str(e)}")
            raise
